name: Deploy Website

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show branch
        run: echo "Running on ${{ github.ref }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set EC2 target
        run: |
          if [[ "${GITHUB_REF}" == *main* ]]; then
            echo "DEPLOY_HOST=${{ secrets.EC2_HOST }}" >> $GITHUB_ENV
            echo "DEPLOY_KEY=${{ secrets.EC2_KEY }}" >> $GITHUB_ENV
          else
            echo "DEPLOY_HOST=${{ secrets.EC2_HOST_TEST }}" >> $GITHUB_ENV
            echo "DEPLOY_KEY=${{ secrets.EC2_KEY_TEST }}" >> $GITHUB_ENV
          fi

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ec2-user
          key: ${{ env.DEPLOY_KEY }}
          script: |
            cd /home/ec2-user/${{ github.event.repository.name }}

            echo "===== CLEAN SYNC CODE ====="
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}

            echo "===== FIX PERMISSIONS ====="
            sudo chown -R ec2-user:ec2-user .

            echo "===== STOP OLD CONTAINER ====="
            docker rm -f ${{ github.event.repository.name }} || true

            echo "===== BUILD IMAGE ====="
            docker build -t ${{ github.event.repository.name }} .

            echo "===== RUN CONTAINER ====="
            docker run -d -p 80:80 \
              --name ${{ github.event.repository.name }} \
              ${{ github.event.repository.name }}

            echo "===== RUNNING CONTAINERS ====="
            docker ps

            echo "===== ALL CONTAINERS ====="
            docker ps -a
