name: Deploy Website

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Show branch
        run: echo "Running on ${{ github.ref }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build-check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 (main branch)
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/${{ github.event.repository.name }}
            ls
            cd ${{ github.event.repository.name }}
            ls
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}
            sudo chown -R ec2-user:ec2-user .
            docker rm -f ${{ github.event.repository.name }} || true
            docker build -t ${{ github.event.repository.name }} .
            docker run -d -p 80:80 --name ${{ github.event.repository.name }} ${{ github.event.repository.name }}
            docker ps -a

      - name: Deploy to EC2 (non-main branches)
        if: github.ref != 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_TEST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY_TEST }}
          script: |
            cd /home/ec2-user/${{ github.event.repository.name }}
            ls
            git fetch --all
            git reset --hard origin/${{ github.ref_name }}
            sudo chown -R ec2-user:ec2-user .
            docker rm -f ${{ github.event.repository.name }} || true
            docker build -t ${{ github.event.repository.name }} .
            docker run -d -p 8080:80 --name ${{ github.event.repository.name }} ${{ github.event.repository.name }}
            docker ps -a
